version: "3.9"

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
      - vhosts:/etc/nginx/vhost.d

  proxy-companion:
    image: sebastienheyd/self-signed-proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs:rw

  nginx:
    image: nginx:alpine-slim
    environment:
      VIRTUAL_HOST: "nginx.localtest.me"
      SELF_SIGNED_HOST: "nginx.localtest.me"

volumes:
  vhosts:
